Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.host_name="so-taller"
  config.vm.define "so-taller"
  config.vm.provider "virtualbox" do |v|
  v.memory=1024
  v.name="so-taller"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
